import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class RowdataService {
  public companydata = {
    "Sheet4": [
      {
        "CompanyCode": 1001,
        "DocType": "GM01  ",
        "Description": "Purchase From Vendor (FOC)",
        "PartnerType": "Vendor",
        "AccountGroup": "VENDOR",
        "NumRangeType": "I",
        "NumRangeCode": "P1",
        "Programme": "PURCH               ",
        "StockMovementType": "Debit               ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Credit",
        "RefranceDocType": "VPO1",
        "RefranceProgramme": "Purchase Order",
        "IsTaxApplicable": 0,
        "TaxType": "GST",
        "Price": "SourceDOC",
        "CreditCheck": 0,
        "LedgerUpdate": 1,
        "CreditUpdateCategory": null,
        "ReverseDocType": "RGM01               ",
        "UpdateMap": 1,
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM02",
        "Description": "Purchase From Vendor (BILL)",
        "PartnerType": "Vendor",
        "AccountGroup": "VENDOR",
        "NumRangeType": "I",
        "NumRangeCode": "P1",
        "Programme": "PURCH               ",
        "StockMovementType": "Debit               ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Credit",
        "RefranceDocType": "VPO2",
        "RefranceProgramme": "Purchase Order",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "SourceDOC",
        "CreditCheck": 0,
        "LedgerUpdate": 1,
        "CreditUpdateCategory": null,
        "ReverseDocType": "RGM02               ",
        "UpdateMap": 1,
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM03",
        "Description": "Purchase Return (FOC)",
        "PartnerType": "Vendor",
        "AccountGroup": "VENDOR",
        "NumRangeType": "I",
        "NumRangeCode": "P2",
        "Programme": "PRRET               ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Debit",
        "RefranceDocType": "VPR1",
        "RefranceProgramme": "Purchase Return Order",
        "IsTaxApplicable": 0,
        "TaxType": "GST",
        "Price": "SourceDOC",
        "CreditCheck": 0,
        "LedgerUpdate": 1,
        "CreditUpdateCategory": null,
        "ReverseDocType": "RGM03               ",
        "UpdateMap": 1,
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "19:50.2",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM04",
        "Description": "Purchase Return (BILLING)",
        "PartnerType": "Vendor",
        "AccountGroup": "VENDOR",
        "NumRangeType": "I",
        "NumRangeCode": "P2",
        "Programme": "PRRET               ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Debit",
        "RefranceDocType": "VPR2",
        "RefranceProgramme": "Purchase Return Order",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "SourceDOC",
        "CreditCheck": 0,
        "LedgerUpdate": 1,
        "CreditUpdateCategory": null,
        "ReverseDocType": "RGM04               ",
        "UpdateMap": 1,
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "19:50.2",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM05",
        "Description": "Stock Transfer",
        "PartnerType": "BRANCH",
        "AccountGroup": "BRANCH",
        "NumRangeType": "I",
        "NumRangeCode": "S1",
        "Programme": "STN                 ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "STR1",
        "RefranceProgramme": "Transfer Order",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "SourceDOC",
        "CreditCheck": 0,
        "LedgerUpdate": 0,
        "CreditUpdateCategory": null,
        "ReverseDocType": "RGM05               ",
        "UpdateMap": 0,
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM06",
        "Description": "Stock Transfer GRN",
        "PartnerType": "BRANCH",
        "AccountGroup": "BRANCH",
        "NumRangeType": "I",
        "NumRangeCode": "S2",
        "Programme": "STNGRN              ",
        "StockMovementType": "Debit               ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "GM05",
        "RefranceProgramme": "Stock Transfer",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "SourceDOC",
        "CreditCheck": 0,
        "LedgerUpdate": 0,
        "CreditUpdateCategory": null,
        "ReverseDocType": "RGM06               ",
        "UpdateMap": 1,
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM07",
        "Description": "Retailer",
        "PartnerType": "Customer",
        "AccountGroup": "RETAIL",
        "NumRangeType": "I",
        "NumRangeCode": "S3",
        "Programme": "Quotation           ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Debit",
        "RefranceDocType": "NSO1",
        "RefranceProgramme": "Quotation",
        "IsTaxApplicable": 0,
        "TaxType": "GST",
        "Price": "PriceList",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM071",
        "Description": "Sales ( FOC)",
        "PartnerType": "Customer",
        "AccountGroup": "AASP,ACP,EASP       ",
        "NumRangeType": "I",
        "NumRangeCode": "S3",
        "Programme": "SALES               ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Debit",
        "RefranceDocType": "NSO1",
        "RefranceProgramme": "Sales Order",
        "IsTaxApplicable": 0,
        "TaxType": "GST",
        "Price": "PriceList",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "null",
        "ReverseDocType": "null                ",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM08",
        "Description": "Sales (Billing)",
        "PartnerType": "Customer",
        "AccountGroup": "AASP,ACP,EASP       ",
        "NumRangeType": "I",
        "NumRangeCode": "S4",
        "Programme": "SALES               ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Debit",
        "RefranceDocType": "NSO2",
        "RefranceProgramme": "Sales Order",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "PriceList",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "null",
        "ReverseDocType": "null                ",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM09",
        "Description": "Customer GRN",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "P3",
        "Programme": "CUSTGRN             ",
        "StockMovementType": "Debit               ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "GM07,GM08",
        "RefranceProgramme": "Sales",
        "IsTaxApplicable": 0,
        "TaxType": "GST",
        "Price": "null",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "null",
        "ReverseDocType": "null                ",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM10",
        "Description": "Customer DC",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "P4",
        "Programme": "CUSTDC              ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": 0,
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM11",
        "Description": "Sales return From Customer (FOC)",
        "PartnerType": "Customer",
        "AccountGroup": "AASP,ACP,EASP       ",
        "NumRangeType": "I",
        "NumRangeCode": "P5",
        "Programme": "SALESRET            ",
        "StockMovementType": "Debit               ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Credit",
        "RefranceDocType": "GM10",
        "RefranceProgramme": "Customer DC",
        "IsTaxApplicable": 0,
        "TaxType": "GST",
        "Price": "null",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "null",
        "ReverseDocType": "null                ",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM12",
        "Description": "Customer Purchase Return Billing",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "P6",
        "Programme": "CUSTDC              ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM13",
        "Description": "Customer GRN Billing",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "P7",
        "Programme": "CUSTGRN             ",
        "StockMovementType": "Debit               ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "GM12",
        "RefranceProgramme": "Customer DC",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "null",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "null",
        "ReverseDocType": "null                ",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM14",
        "Description": "Customer Debit Note",
        "PartnerType": "Customer",
        "AccountGroup": "AASP,ACP,EASP       ",
        "NumRangeType": "I",
        "NumRangeCode": "P8",
        "Programme": "DBNOTE              ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Debit",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "GM15",
        "Description": "Customer Credit Not",
        "PartnerType": "Customer",
        "AccountGroup": "AASP,ACP,EASP       ",
        "NumRangeType": "I",
        "NumRangeCode": "P9",
        "Programme": "CRNOTE              ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Credit",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "NSO1",
        "Description": "Billing Sales Order",
        "PartnerType": "Customer",
        "AccountGroup": "AASP,ACP,EASP       ",
        "NumRangeType": "I",
        "NumRangeCode": "S5",
        "Programme": "SALESORD            ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 1,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": 1,
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "NSO2",
        "Description": "FOC Sales Order",
        "PartnerType": "Customer",
        "AccountGroup": "AASP,ACP,EASP       ",
        "NumRangeType": "I",
        "NumRangeCode": "S6",
        "Programme": "SALESORD            ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 1,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "RP01",
        "Description": "Repack",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "R1",
        "Programme": "ASSMB               ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "SORB",
        "Description": "Service Order Billing",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "A2",
        "Programme": "SVCORD              ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "SORF",
        "Description": "Service Order FOC",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "A1",
        "Programme": "SVCORD              ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "SORP",
        "Description": "Service Order From Branch",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "A3",
        "Programme": "SVCORD              ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "STI1",
        "Description": "Store Transfer Issue",
        "PartnerType": "STORE",
        "AccountGroup": "NULL",
        "NumRangeType": "null",
        "NumRangeCode": "S9",
        "Programme": "STOTRN              ",
        "StockMovementType": "Credit              ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "STO1",
        "Description": "Store Transfer Order",
        "PartnerType": "STORE",
        "AccountGroup": "NULL",
        "NumRangeType": "I",
        "NumRangeCode": "S8",
        "Programme": "STOTRNORD           ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 1,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": 1,
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "STR1",
        "Description": "Store Transfer Receive",
        "PartnerType": "STORE",
        "AccountGroup": "NULL",
        "NumRangeType": "I",
        "NumRangeCode": "T2",
        "Programme": "STOTRNGRN           ",
        "StockMovementType": "Debit               ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "TD01",
        "Description": "Teardown",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "T1",
        "Programme": "CANNIB              ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 0,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      },
      {
        "CompanyCode": 1001,
        "DocType": "TSO1",
        "Description": "Transfer Order",
        "PartnerType": "Plant",
        "AccountGroup": "PLNT                ",
        "NumRangeType": "I",
        "NumRangeCode": "S7",
        "Programme": "TRANORD             ",
        "StockMovementType": "Nothing             ",
        "MoveToBlockStock": 1,
        "PartnetLedgerUpdateType": "Nothing",
        "RefranceDocType": "NULL",
        "RefranceProgramme": "NULL",
        "IsTaxApplicable": "NULL",
        "TaxType": "GST",
        "Price": "NULL",
        "CreditCheck": "NULL",
        "LedgerUpdate": "NULL",
        "CreditUpdateCategory": "NULL",
        "ReverseDocType": "NULL",
        "UpdateMap": "NULL",
        "TransitFlag": "NULL",
        "UpdateReceiveStockAtRef": "NULL",
        "FromStoreCode": "NULL",
        "SameToStoreFlag": "NULL",
        "ToStoreCode": "NULL",
        "Approvalrequired": "NULL",
        "AutoPickupDocked": "NULL",
        "AutoPickupDockedType": "NULL",
        "CreditUpdate": "NULL",
        "CreditExposureUpdateType": "NULL",
        "ClientCode": 1,
        "CreatedBy": "MDM",
        "CreatedDate": "15:24.0",
        "ModifiedBy": "NULL",
        "ModifiedDate": "NULL",
        "IsDeleted": 0
      }
    ]
  }

  constructor() { }
}
