export enum FieldType {
  Text = "text",
  TextArea = "textarea",
  Email = "email",
  phone = "phone",
  Password = "password",
  Picklist = "picklist",
  multiPickList = "multipicklist"
}

export enum ACTIONENUM {
  EDIT = "EDIT",
  ADD = "ADD",
  IMPORT  = "IMPORT",
  EXPORT = "EXPORT",
  GRIDROWADD = "GRIDROWADD",
  DELETE="DELETE",
  GRIDROWVIEW = "GRIDROWVIEW",
}


export enum FieldName {
  orgrolename = "orgrolename",
  orgroledescription = "orgroledescription",
}


export enum Controller {
  Register = 'Register/',
  Menu = 'Menu/',
  SystemAdministrator = 'SystemAdministrator/',
  Custom = 'Custom/',
  Dynamic = 'Dynamic/',
  GSX = 'GSX/',
  SAP = 'SAP/',
  Report = 'Report/',
  EmailValidator = 'EmailValidator/',
  Guest = 'Guest/',
  PaymentGateway = 'PaymentGateway/',
  EInvoice = 'EInvoice/',
  IncomingInvoice = 'IncomingInvoice/',
  LeadManagement = 'LeadManagement/',
  Reservation = "Reservation/"

}


export enum AppRouter {
  Auth = 'auth',
  Login = 'login',
  Dashboard = 'dashboard',
  ConfigurationSetting = 'configurationsetting',
  Add = 'add',
  Edit = 'edit',  
  Contact = 'contact',
  TokenGenerate = 'tokenGenerate',
  Marketing = 'marketing',
  Campaign = 'campaign',
  Lead = 'lead',
  Quote = 'quote',
  Opportunity = 'opportunity',

  Sales = 'sales',
  Customer = 'customer',
  SalesOrder = 'salesorder',
  SalesInvoice = 'salesinvoice',
  SalesReturnOrder = 'salesreturnorder',
  SalesReturn = 'salesreturn',
  SalesCreditDemo='salescreditdemo',
  SalesDebitDemo='salesdebitdemo',
  
  Purchase='purchase',
  PurchaseOrder = 'purchaseorder',
  PurchaseInvoice = 'purchaseinvoice',
  PurchaseReturnOrder = 'purchasereturnOrder',
  PurchaseReturn = 'purchasereturn',
  PurchaseCreditDemo='purchasecreditdemo',
  PurchaseDebitDemo='purchasedebitdemo',

  Accounts = 'accounts',
  FiscalYear = 'fiscalyear',
  ChartOfAccount = 'chartofaccount',
  OutgoingPayment = 'outgoingpayment',
  PaymentReceipt = 'paymentreceipt',

  WorkOrderMgmt='workordermgmt',
  JOBManagement='jobmanagement',
  JOBDOCType='jobdoctype',
  AssignJOBToTechnician='assignjobtotechnician',
  AssignMaterialToTechnician='assignmaterialtotechnician',
  ReceiveMaterialFromTechnician='receivematerialfromtechnician',
  Quatation='quatation',
  RepairProcess='repairprocess',
  EscalationOutChallan='escalationoutchallan',
  EscalationReceiveChallan='escalationreceivechallan',
  EscalationReturnChallan='escalationreturnchallan',
  EscalationReturnReceiveChallan='escalationreturnreceivechallan',

  Inventory = 'inventory',
  TransferOrder = 'transferorder',
  StockTransferNote = 'stocktransfernote',
  Teardown='teardown',
  Repack='repack',
  StockAdjustment='stockadjustment',
  BinTransfer='bintransfer',
 
  Masters="masters",
  MaterialMaster = 'materialmaster',
  Resources='resources',
  PriceGroup='pricegroup',
  CompanyDetails = 'companydetails',
  Vendor = 'vendor',
  WarehouseMaster = 'warehousemaster',
  CompanyMaterialMapping='companymaterialmapping',
  MaterialTrackingProfiler='materialtrackingprofiler',
  Division='division',
  MaterialType='materialtype',
  MaterialCategory='materialcategory',
  ModelMaster='modelmaster',
  BrandMaster='brandmaster',
  MaterialSpecificationDimension='materialspecificationdimension',
  MaterialSpecificationValues='materialspecificationvalues',
  MaterialSpecification='materialspecification',
  StockIndicator='stockindicator',
  BillsOfMaterial='billsofmaterial',
  ResourcesCompanyMapping='resourcescompanymapping',
  PricingCondition='pricingcondition',
  DiscountGroup='discountgroup',
  DiscountConditions='discountconditions',
  UOM='uom',
  TerritoryHierarchy='territoryhierarchy',
  TaxType='taxtype',
  CountryMaster='countrymaster',
  StateMaster='statemaster',
  VatPostingSetup='vatpostingsetup',
  GSTComponent='gstcomponent',
  SubAccountingPeriod='subaccountingperiod',
  GSTConfiguration='gstconfiguration',
  GSTPostingSetup='gstpostingsetup',
  GSTGroup='gstgroup',
  GSTSetup='gstsetup',
  GSTClaimSetOff='gstclaimsetoff',
  IssueCategory='issuecategory',
  SymptomMaster='symptommaster',
  SymptomGroup='symptomgroup',
  DefectMaster='defectmaster',
  DefectGroup='defectgroup',
  RepairMaster='repairmaster',
  RepairGroup='repairgroup',
  ServiceConfigutaion='serviceconfigutaion',
  NumRange='numrange',

  SystemAdministrator = 'systemadministrator',
  UserManagement = 'usermanagement',
  OrgRoleManagement = 'orgrolemanagement',
  JOBRoleManagement = 'jobrolemanagement',
  ProfileSetting = 'profilesetting',

  Settings = 'settings',
  PickList='picklist',
  SalesOrderDocType = 'saleorderdoctype',
  PurchaseOrderDocType = 'purchaseorderdoctype',
  SalesInvoiceDocType = 'salesinvoicedoctype',
  PurchaseInvoiceDocType = 'purchaseinvoicedoctype',
  TerritorySetting='territorysetting',
  NumRangeSettings='numrangesettings',

  Services = 'services',
  PriceList = 'pricelist',
  GRN = 'grn',
  SalesReturnOrderDocType = 'salesreturnorderdoctype',
  PurchaseReturnOrderDocType = 'purchasereturnorderdoctype',
  GSTSetting = 'gstsetting',
  UserList = 'userlist',
  UserAdd = 'useradd',
  OrgRoleList = 'orgrolelist',
  OrgRoleAdd = 'orgroleadd',
  JobRoleList = 'jobrolelist',
  JobRoleAdd = 'jobroleadd',
  AddEditProfileSetting = 'addeditprofilesetting',

  SubMenu='submenu',
  Master="master",
  MasterContent="mastercontent",
}

export enum BreadCumb {
  Auth = 'Auth',  
  Login = 'Login',
  Dashboard = 'Dashboard',
  ConfigurationSetting = 'ConfigurationSetting',
  Add = 'Add',
  Edit = 'Edit',  
  Contact = 'Contact',

  Marketing = 'Marketing',
  Campaign = 'Campaign',
  Lead = 'Lead',
  Quote = 'Quote',
  Opportunity = 'Opportunity',

  Sales = 'Sales',
  Customer = 'Customer',
  SalesOrder = 'Sales Order',
  SalesInvoice = 'Sales Invoice',
  SalesReturnOrder = 'Sales Return Order',
  SalesReturn = 'Sales Return',
  SalesCreditDemo='Sales Credit Demo',
  SalesDebitDemo='Sales Debit Demo',
  
  Purchase='Purchase',
  PurchaseOrder = 'Purchase Order',
  PurchaseInvoice = 'Purchase Invoice',
  PurchaseReturnOrder = 'Purchase Return Order',
  PurchaseReturn = 'Purchase Return',
  PurchaseCreditDemo='Purchase Credit Demo',
  PurchaseDebitDemo='Purchase Debit Demo',

  Accounts = 'Accounts',
  FiscalYear = 'Fiscal Year',
  ChartOfAccount = 'Chart Of Account',
  OutgoingPayment = 'Outgoing Payment',
  PaymentReceipt = 'Payment Receipt',

  WorkOrderMgmt='Work Order Mgmt',
  JOBManagement='JOB Management',
  JOBDOCType='JOB DOC Type',
  AssignJOBToTechnician='Assign JOB To Technician',
  AssignMaterialToTechnician='Assign Material To Technician',
  ReceiveMaterialFromTechnician='Receive Material From Technician',
  Quatation='Quatation',
  RepairProcess='Repair Process',
  EscalationOutChallan='Escalation Out Challan',
  EscalationReceiveChallan='Escalation Receive Challan',
  EscalationReturnChallan='Escalation Return Challan',
  EscalationReturnReceiveChallan='Escalation Return ReceiveChallan',

  Inventory = 'Inventory',
  TransferOrder = 'Transfer Order',
  StockTransferNote = 'Stock Transfer Note',
  Teardown='Tear down',
  Repack='Repack',
  StockAdjustment='Stock Adjustment',
  BinTransfer='Bin Transfer',
 
  Masters="Masters",
  MaterialMaster = 'Material Master',
  Resources='Resources',
  PriceGroup='Price Group',
  CompanyDetails = 'Company Details',
  Vendor = 'Vendor',
  WarehouseMaster = 'Warehouse Master',
  CompanyMaterialMapping='Company Material Mapping',
  MaterialTrackingProfiler='Material Tracking Profiler',
  Division='Division',
  MaterialType='Material Type',
  MaterialCategory='Material Category',
  ModelMaster='Model Master',
  BrandMaster='Brand Master',
  MaterialSpecificationDimension='Material Specification Dimension',
  MaterialSpecificationValues='Material Specification Values',
  MaterialSpecification='Material Specification',
  StockIndicator='Stock Indicator',
  BillsOfMaterial='Bills Of Material',
  ResourcesCompanyMapping='Resources Company Mapping',
  PricingCondition='Pricing Condition',
  DiscountGroup='Discount Group',
  DiscountConditions='Discount Conditions',
  UOM='UOM',
  TerritoryHierarchy='Territory Hierarchy',
  TaxType='Tax Type',
  CountryMaster='Country Master',
  StateMaster='State Master',
  VatPostingSetup='Vat Posting Setup',
  GSTComponent='GST Component',
  SubAccountingPeriod='Sub Accounting Period',
  GSTConfiguration='GST Configuration',
  GSTPostingSetup='GST PostingSetup',
  GSTGroup='GST Group',
  GSTSetup='GST Setup',
  GSTClaimSetOff='GST Claim Set-Off',
  IssueCategory='Issue Category',
  SymptomMaster='Symptom Master',
  SymptomGroup='Symptom Group',
  DefectMaster='Defect Master',
  DefectGroup='Defect Group',
  RepairMaster='Repair Master',
  RepairGroup='Repair Group',
  ServiceConfigutaion='Service Configutaion',
  NumRange='Num Range',

  SystemAdministrator = 'System Administrator',
  UserManagement = 'User Management',
  OrgRoleManagement = 'OrgRole Management',
  JOBRoleManagement = 'JOBRole Management',
  ProfileSetting = 'Profile Setting',

  Settings = 'Settings',
  PickList='Pick List',
  SalesOrderDocType = 'Sales Order Doc Type',
  PurchaseOrderDocType = 'Purchase Order Doc Type',
  SalesInvoiceDocType = 'Sales Invoice Doc Type',
  PurchaseInvoiceDocType = 'Purchase Invoice Doc Type',
  TerritorySetting='Territory Setting',
  NumRangeSettings='NumRange Settings',



  Services = 'Services',
  PriceList = 'Price List',
  GRN = 'GRN',
  SalesReturnOrderDocType = 'Sales Return Order Doc Type',
  PurchaseReturnOrderDocType = 'Purchase Return Order Doc Type',
  GSTSetting = 'GST Setting',
}

export enum EVENTTYPE {
  ACTIVATION = "ACTIVATION",
  ASSIGNTO = "ASSIGNTO",
  RESETGRID = "RESETGRID"
}